# Site settings

title: Daniel P Koch
subtitle: "Blog"
logo: "/assets/images/logo.svg"
description: >-
  I'm a PhD student working on unmanned air vehicles and, more generally,
  autonomous systems. Welcome to my blog!
baseurl: ""
url: "https://blog.danielpkoch.com"
repository: "dpkoch/blog"
locale: "en-US"

name: "Daniel Koch"
email: daniel.p.koch@gmail.com
github_username:  dpkoch

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

search: true

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-archives

comments:
  provider: "disqus"
  disqus:
    shortname: "danielpkoch"

# Theme settings (minimal-mistakes)
author:
  name: "Daniel Koch"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I'm a PhD student working on autonomous systems and unmanned air vehicles"
  location: "Provo, Utah"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://danielpkoch.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dpkoch"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielpkoch/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://danielpkoch.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dpkoch"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielpkoch/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single